### ISSUE TITLE
Доработка поиска

### ISSUE THREAD

**Issue by Lefrin** [rivnefish/rivnefish#110]
При поиске водоема когда в строке пишешь например "Ми" или "Б"- тебе показывает на карте водоемы но названия в строке поиска их не пишет. Это очень не удобно, ты должен клацать все водоемы на карте чтоб найти тот что у тебя крутиться на уме но ты его не помнишь. 
Или добавить список водоемов сбоку и сверху поиск.

**Comment by stal1n274** [comment]
Ми винесемо пошук за назвою в окремий сайдбар. По-замовчуванню там буде не весь список всіх водойм, а водойми зі свіжими звітами. Як тільки у вікні пошуку буде щось введено - відразу формуватиметься список знайдених водойм. Фільтр почне діяти після другого введеного символу.

**Comment by Lefrin** [comment]
"Як тільки у вікні пошуку буде щось введено - відразу формуватиметься список знайдених водойм. Фільтр почне діяти після другого введеного символу." - такой вариант дума полностью сойдет.

Что по второму вопросу?

**Comment by lynxrv21** [comment]
This message was created automatically by mail delivery software at Junk Email Filter. 

The message from "Lefrin [Masked]" <FWD-737QTYSMENAIYCQANIQDDYBDEA4GOAJYEBAUYCATUAZUEADNBJAALMIBBRRCGGBEM56FNL2I7EAOMCAONDNAFSCAEMZ7MIR4I67EXIQMUR2QQALYBQFBCSDUXNCE6A52DVZCY5AKEACWEILAAPAAOUAE2AAZAAGQAWKCOULAHZQDMYBLJ7ASZKBNGAACAABA@opayq.com> is being returned by server opayq-outbound.junkemailfilter.com on Fri, 09 Jun 2017 12:13:52 -0700

A message that you sent could not be delivered to all of its recipients.

NOTE: And this is important - Junk Email Filter is a front end spam filtering service. We accept email for our customers, filter it, and pass the good email on. Sometimes when we forward email as good the server we forward to rejects it. Generally if you are getting this message it is because the server we forwarded to  * NOT JUNK EMAIL FILTER * has rejected the message.

If you see below the phrase "error from remote mail server" then it is the server who we are forwarding to, NOT US who is rejecting the email. Read the reason carefully and see if you can correct the cause of the rejection.

The following address(es) failed:

  lynxrv@mail.ru
    host mxs.mail.ru [94.100.180.104]
    SMTP error from remote mail server after HELO opayq-out-00.junkemailfilter.com
    opayq-outbound.ctyme.com: 500 Syntax error

**Comment by stal1n274** [comment]
Забудь про @mail.ru як про страшний, неспокійний з холодним потом сон

Щодо другого питання, ми його виділили в окрему задачу: https://github.com/rivnefish/rivnefish/issues/111

**Comment by Lefrin** [comment]
Это моя спамерская почта - отличная штука. Вся регистрация на неизвсных ресах там)

**Comment by ttp** [comment]
Після 3-го символу

**Comment by stal1n274** [comment]
Імплементовано в #116
